# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # run shellcheck
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      # run lintmarkdown
      - name: Lint Markdown
        uses: tomwhross/write-good-action@v1.6
            
        
